title: BetterPT Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://cstate.mnts.lt'
params:
  alwaysKeepBrandColor: true
  brand: '#0a0c0f'
  categories:
    - closed: true
      description: Our web applications
      name: Web Applications
    - closed: true
      description: Our APIs
      name: APIs
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: >-
    BetterPT Status Page. We continuously monitor the status of our services and
    if there are any interruptions, a note will be posted here.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: /img/bptlogo.jpeg
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '15:04 â€” Jan 2'
  systems: []
  useLargeHeaderDesign: true
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
